install:
  - npm install
  - grunt build
  - bower install

script: 
  - grunt tests

notifications:
  slack:
    rooms:
      - loadingplay:CQg5lsp4Hi9OdB79EZndUnOX#bug
    on_success: never # default: always
    on_failure: always # default: always
